config/routes.rb
SampleApp::Application.routes.draw do

  resources :aspects

  resources :events

  devise_for :users

  mount DiasporaClient::App.new => '/auth/diaspora'
  
  resources :activities

  match 'me' => 'activities#me'
  match 'activities/:id/contacts' => 'activities#contacts' #, :as => :activityname # why I don't comment?! 
  match 'activities/:id/stream' => 'activities#stream'
  match 'activities/:id/last' => 'activities#last'
  match 'activities/:id/week' => 'activities#week'
  match 'activities/:id/today' => 'activities#today'
  match 'activities/:id/upload' => 'activities#upload'
  match 'activities/:id' => 'activities#new'
  match 'profiles/:id' => 'activities#profiles'
  match 'group/' => 'activities#group' # creates a new group of people for a specific activity. It does not need a user to operate, but just to authenticate
  
  match 'geniehub/status' => 'geniehub#status' # function to return the current status to a javascript call 
  match 'geniehub/listener' => 'geniehub#listener'
  
  
  namespace :apiv1 do
      defaults :format => "json" do
		match 'aspects/add'   => 'aspects#add', :via => [:get, :post]  
		match 'aspects/delete'   => 'aspects#delete'
		match 'contacts/all'   => 'contacts#all'
        resources :aspects, :posts, :contacts, :profiles, :users
      end
  end

  
  resources :status # todelete
  
  match 'exit' => 'home#logout', :as => :logout
  
  resources :upload
  
  root :to => "home#show"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html
  
  

  def show
    if current_user
      flash[:notice] = "YAY!"
      @current_user = current_user
      render "success" 
    else
      user = User.find_by_diaspora_id('communityawvej@idea.itu.dk:3000')
      request.env["warden"].set_user(user, :scope => :user, :store => true)
      render "success" 
    end
  end
  
 

  
  
def logout
  request.env['warden'].logout
  render "show"
end


end

app/views/home/show.html.haml
= content_for :title => "Poppelvænget"
#content
  Login
  = form_tag('/auth/diaspora', :method => :get) do
    = text_field_tag :diaspora_id, '', :placeholder => "Diaspora ID"
    = submit_tag :connect
 
#activities 

app/views/home/success.html.haml
= content_for :title, "Poppelvænget"
-#= @current_user.diaspora_id
-#= link_to "Sign out", logout_url

-#</br>
-#= link_to 'status' , 'status/'
-#= link_to 'create' , 'create/'

#content
  %iframe{:src=>"http://idea.itu.dk/augustwimmersvej/noticeboard", :width=>"100%", :height=>"100%"}
    %p Your browser does not support iframes.

=render "shared/bar"
        